# Generated by Django 4.2.4 on 2023-12-06 05:04

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': '目录', 'verbose_name_plural': '目录'},
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.folder'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('parent', 'name')},
        ),
    ]
