# Generated by Django 4.2.4 on 2023-12-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_folder_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title', 'folder')},
        ),
    ]
