# Generated by Django 4.2.4 on 2023-12-09 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updated_at',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='updated_at',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='updated_at',
            new_name='update_time',
        ),
        migrations.AddField(
            model_name='folder',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
