# Generated by Django 4.2.4 on 2023-12-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_friend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': '友链', 'verbose_name_plural': '友链'},
        ),
    ]
