# Generated by Django 4.2.4 on 2023-12-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_friend_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
