# 词条的期望值和标准差
ATTACK_MEAN = 200
ATTACK_STD = 10
ATTACK_PERCENT_MEAN = 5
ATTACK_PERCENT_STD = 1
DEFENSE_MEAN = 200
DEFENSE_STD = 10
DEFENSE_PERCENT_MEAN = 5
DEFENSE_PERCENT_STD = 1
HEALTH_MEAN = 5000
HEALTH_STD = 100
HEALTH_PERCENT_MEAN = 5
HEALTH_PERCENT_STD = 1
CRITICAL_RATE_MEAN = 5
CRITICAL_RATE_STD = 2
CRITICAL_DAMAGE_MEAN = 50
CRITICAL_DAMAGE_STD = 10

# 装备等级上限
EQUIPMENT_LEVEL_LIMIT = 10

# 角色装备上限
CHARACTER_EQUIPMENT_LIMIT = 6

# 词条评分及格线
TERM_PASSING_LINE = 60

# 角色等级 = 装备等级上限 * 装备数量上限
CHARACTER_LEVEL_LIMIT = EQUIPMENT_LEVEL_LIMIT * CHARACTER_EQUIPMENT_LIMIT

# 初始化时创建的角色数量

INITIAL_CHARACTER_COUNT = 10
