# Generated by Django 4.2.7 on 2023-11-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.FloatField(default=200)),
                ('defense', models.FloatField(default=100)),
                ('health', models.FloatField(default=1000)),
                ('critical_rate', models.FloatField(default=5)),
                ('critical_damage', models.FloatField(default=50)),
                ('birth', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.FloatField(default=0)),
                ('attack_level', models.IntegerField(default=0)),
                ('attack_percent', models.FloatField(default=0)),
                ('attack_percent_level', models.IntegerField(default=0)),
                ('defense', models.FloatField(default=0)),
                ('defense_level', models.IntegerField(default=0)),
                ('defense_percent', models.FloatField(default=0)),
                ('defense_percent_level', models.IntegerField(default=0)),
                ('health', models.FloatField(default=0)),
                ('health_level', models.IntegerField(default=0)),
                ('health_percent', models.FloatField(default=0)),
                ('health_percent_level', models.IntegerField(default=0)),
                ('critical_rate', models.FloatField(default=0)),
                ('critical_rate_level', models.IntegerField(default=0)),
                ('critical_damage', models.FloatField(default=0)),
                ('critical_damage_level', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='game.characterinstance')),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.equipmentprototype')),
            ],
        ),
        migrations.AddField(
            model_name='characterinstance',
            name='prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.characterprototype'),
        ),
    ]
